# Generated by Django 6.1.1 on 2026-09-24 09:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=120, unique=True)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "Categories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "condition",
                    models.CharField(
                        choices=[
                            ("NEW", "Brand New"),
                            ("LIKE_NEW", "Like New"),
                            ("GOOD", "Good Condition"),
                            ("FAIR", "Fair / Usable"),
                            ("REPAIRABLE", "Needs Repair / Repairable"),
                        ],
                        default="GOOD",
                        max_length=20,
                    ),
                ),
                (
                    "is_repairable",
                    models.BooleanField(
                        default=False,
                        help_text="Flag this item if it can be repaired, restored, or upcycled.",
                    ),
                ),
                (
                    "repair_details",
                    models.TextField(
                        blank=True,
                        help_text="Describe what needs repair or ideas for restoration.",
                    ),
                ),
                (
                    "pickup_location",
                    models.CharField(
                        help_text="Pickup landmark, neighborhood, or general area.",
                        max_length=255,
                    ),
                ),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="items/%Y/%m/"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("AVAILABLE", "Available"),
                            ("REQUESTED", "Request Pending"),
                            ("GIVEN_AWAY", "Given Away"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="AVAILABLE",
                        max_length=20,
                    ),
                ),
                (
                    "moderation_status",
                    models.CharField(
                        choices=[
                            ("APPROVED", "Approved"),
                            ("PENDING", "Pending Moderation"),
                            ("FLAGGED", "Flagged for Review"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="APPROVED",
                        max_length=20,
                    ),
                ),
                ("moderation_notes", models.TextField(blank=True)),
                ("views_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="items",
                        to="app.category",
                    ),
                ),
                (
                    "donor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="donated_items",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("INAPPROPRIATE", "Inappropriate or Offensive Content"),
                            ("SPAM_COMMERCIAL", "Spam / Commercial Selling / Not Free"),
                            ("HAZARDOUS", "Hazardous or Prohibited Item"),
                            ("MISLEADING", "Misleading Information or Condition"),
                            ("OTHER", "Other Community Guideline Violation"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "details",
                    models.TextField(help_text="Please describe the issue in detail."),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending Review"),
                            ("RESOLVED", "Resolved (Action Taken)"),
                            ("DISMISSED", "Dismissed (Listing Approved)"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("admin_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="app.item",
                    ),
                ),
                (
                    "reported_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bio",
                    models.TextField(
                        blank=True,
                        help_text="Tell the community a little about yourself.",
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=30)),
                (
                    "location",
                    models.CharField(
                        blank=True, help_text="City or neighborhood.", max_length=150
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(blank=True, null=True, upload_to="avatars/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ItemRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        help_text="Introduce yourself and explain why you'd like this item or when you can collect it."
                    ),
                ),
                (
                    "contact_info",
                    models.CharField(
                        blank=True,
                        help_text="Phone number or preferred contact method",
                        max_length=150,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("ACCEPTED", "Accepted"),
                            ("REJECTED", "Rejected"),
                            ("COMPLETED", "Collected / Completed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "donor_notes",
                    models.TextField(
                        blank=True, help_text="Instructions or response from the donor"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requests",
                        to="app.item",
                    ),
                ),
                (
                    "requester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="item_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("item", "requester")},
            },
        ),
    ]
