# Generated by Django 6.1.1 on 2026-09-26 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_itemimage"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="itemimage",
            options={"ordering": ["-is_cover", "id"]},
        ),
        migrations.AddField(
            model_name="itemimage",
            name="is_cover",
            field=models.BooleanField(default=False),
        ),
    ]
