# Generated by Django 6.1.1 on 2026-09-28 09:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_report_reported_user_userprofile_is_verified_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="email_verified",
            field=models.BooleanField(
                default=False,
                help_text="Designates whether the user verified their email address via OTP.",
            ),
        ),
        migrations.CreateModel(
            name="EmailOTP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("code", models.CharField(max_length=6)),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("REGISTRATION", "Account Registration"),
                            ("PASSWORD_RESET", "Password Reset"),
                            ("EMAIL_CHANGE", "Email Address Change"),
                        ],
                        default="REGISTRATION",
                        max_length=30,
                    ),
                ),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                ("max_attempts", models.PositiveSmallIntegerField(default=5)),
                ("is_used", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="otp_codes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Email OTP",
                "verbose_name_plural": "Email OTPs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "purpose", "is_used"],
                        name="app_emailot_user_id_70c244_idx",
                    ),
                    models.Index(
                        fields=["email", "code"], name="app_emailot_email_d56ba6_idx"
                    ),
                ],
            },
        ),
    ]
